config/routes.rb
Rails.application.routes.draw do
  root "restaurants#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :restaurants, shallow: true do
    resources :reviews do
      resources :endorsements
    end
  end

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base

  USER_ALREADY_ENDORSED_ERROR_MESSAGE = "Cannot re-endorse review"

  validates :user, uniqueness: {scope: :review, message: USER_ALREADY_ENDORSED_ERROR_MESSAGE}
  validates :user, presence: true
  belongs_to :user
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, length: {minimum: 3}, uniqueness: true
  belongs_to :user
  validates :user, presence: true
  has_many :reviews, dependent: :destroy
  has_many :user_reviews, through: :reviews, source: :user
  has_attached_file :image, :styles => {:medium => '300x300>', :thumb => '100x100>'}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image,:content_type => /\Aimage\/.*\Z/

  def build_review(review_params, user)
    review = Review.new(review_params)
    review.restaurant = self
    review.user = user
    review.save
  end

  def average_rating
    reviews.average(:rating).to_i
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

  USER_ALREADY_REVIEWED_ERROR_MESSAGE = "has reviewed this restaurant already"

  validates :user, uniqueness: {scope: :restaurant, message: USER_ALREADY_REVIEWED_ERROR_MESSAGE}
  validates :user, presence: true
  validates :rating, inclusion: (1..5)
  belongs_to :restaurant
  belongs_to :user
  has_many :endorsements

  def endorse_by(user, endorsement_class: Endorsement)
    endorsement = endorsement_class.new(user: user, review: self)
    return endorsement.errors.messages[:user].first if !endorsement.save
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :restaurants
  has_many :reviews
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant

  has_many :endorsements
  has_many :endorsed_reviews, through: :endorsements, source: :review


  def self.from_omniauth(auth)
    where(uid: auth.uid, provider: auth.provider).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def creator_of?(restaurant)
    restaurants.include? restaurant
  end

  def reviewer_of?(restaurant)
   reviewed_restaurants.include? restaurant
  end

  def author_of?(review)
   reviews.include? review
  end

  def endorser_of?(review)
    endorsed_reviews.include? review
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

  before_action :authenticate_user!

  def create
    review = Review.find(params[:review_id])
    flash[:alert] = review.endorse_by(current_user)
    render json: {new_endorsement_count: review.endorsements.count}
    # redirect_to restaurants_path
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def restaurant_params
    params.require(:restaurant).permit([:name, :image])
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    if !current_user.creator_of?(@restaurant)
      flash[:alert] = 'Cannot edit restaurant'
      redirect_to restaurants_path
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    if !current_user.creator_of?(@restaurant)
      flash[:alert] = 'Cannot delete restaurant'
    else
      @restaurant.destroy
      flash[:notice] = 'Restaurant deleted successfully'
    end
    redirect_to restaurants_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

def new
  if current_user.nil?
    flash[:alert] = 'You need to sign in or sign up before continuing.'
    redirect_to restaurants_path
    return
  end
  @restaurant = Restaurant.find(params[:restaurant_id])
  if current_user.reviewer_of?(@restaurant)
    flash[:alert] = 'Cannot re-review restaurant'
    redirect_to restaurants_path
    return
  end
  @review = Review.new

 end

  def create
    restaurant = Restaurant.find(params[:restaurant_id])
    restaurant.build_review(review_params, current_user)
    redirect_to restaurants_path
  end

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    remainder = 5 - (rating.round)
    '★' * rating.round + '☆' * remainder
  end
end

app/views/layouts/JUNK application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Yelp Clone
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    %body
    = notice
    = yield

app/views/restaurants/edit.html.haml
=form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.submit

app/views/restaurants/index.html.haml
- if @restaurants.any?
  - @restaurants.each do |restaurant|
    = link_to restaurant.name, restaurant_path(restaurant)
    - if restaurant.image_file_name
      = image_tag restaurant.image.url(:thumb)
    = link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)
    = link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete
    = link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant)

    %h3
      Reviews for
      = restaurant.name

    - if restaurant.reviews.any?
      %ul
        - restaurant.reviews.each do |review|
          %li
            #{review.thoughts} Average rating: #{star_rating(restaurant.average_rating)}
            = link_to "Endorse", review_endorsements_path(review), class: 'endorsements-link'
            %span.endorsements_count= review.endorsements.count
            = 'endorsement'.pluralize review.endorsements.count

            %strong= review.rating
            \/5
    - else
      %p No reviews



- else
  No restaurants yet!

= link_to 'Add a restaurant', new_restaurant_path

app/views/restaurants/new.html.haml
- if @restaurant.errors.any?
  %section#errors
    %h2
      = pluralize @restaurant.errors.count, "error"
      prohibited this restaurant from being saved:
    %ul
      - @restaurant.errors.full_messages.each do |message|
        %li= message

= form_for @restaurant, html: {multipart: true} do |f|
  = f.label :name
  = f.text_field :name
  = f.file_field :image
  = f.submit

app/views/restaurants/show.html.haml
%p= @restaurant.name
%p= @restaurant.description

%h3
  Reviews for
  = @restaurant.name

- if @restaurant.reviews.any?
  %ul
    - @restaurant.reviews.each do |review|
      %li
        = review.thoughts
        %strong= review.rating
        \/5
- else
  %p No reviews

app/views/reviews/new.html.haml
= form_for [@restaurant, @review] do |f|
  = f.label :thoughts
  = f.text_area :thoughts
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit 'Leave Review'